## Minimal haskell file
language: c
sudo: false

branches:
  only:
    - prolog-out

matrix:
  include:
    - env: SMT="z3" CABAL=1.22 GHC=ghc-7.10.2
      addons: {apt: {packages: [libgmp-dev, happy] }}

cache: 
  directories:
    - $HOME/.stack
    - .stack-work

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$HOME/.cabal/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- travis_retry stack setup
- travis_retry stack install cabal-install
- travis_retry stack install happy
- scripts/travis install_smt "$SMT"

install:
# - scripts/travis install_stack "$STACK"
 - scripts/travis configure_stack "$GHC"
 - scripts/travis setup_ghc
 - scripts/travis install_dependencies

script:
 - scripts/travis do_build # && scripts/travis do_test "$TESTS" "$SMT"

after_failure:
 - scripts/travis dump_fail_logs
